name: flutterfire_cli
description: A command-line application for FlutterFire.
version: 0.3.0-dev.6
homepage: "https://github.com/invertase/flutterfire_cli"

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  ansi_styles: ^0.3.2+1
  args: ^2.3.0
  ci: ^0.1.0
  cli_util: ^0.3.5
  deep_pick: ^0.10.0
  file: ^6.1.2
  interact: ^2.1.1
  meta: ^1.7.0
  path: ^1.8.0
  platform: ^3.0.2
  pub_updater: ^0.2.2
  pubspec: ^2.1.0
  xml: ^5.3.1

dev_dependencies:
  test: ^1.16.0

executables:
  flutterfire:
